main: su.nightexpress.excellentcrates.CratesPlugin
version: '${project.version}'
name: ExcellentCrates
author: NightExpress
desciption: Fully customizable crates with rewards. Enjoy.
depend: [ nightcore ]
softdepend: [ CoinsEngine, DecentHolograms, Vault, PlaceholderAPI, ProtocolLib, WorldGuard ]
api-version: 1.18